services:
  # Container 1: CSDL Microsoft SQL Server 2022
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aka-sqlserver-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AkaSystem@123456
      - MSSQL_PID=Developer
    ports:
      - "14333:1433" # Cổng 14333 bên ngoài chống xung đột 100% với SQL Server sẵn có trên máy
    volumes:
      - mssql_data:/var/opt/mssql

  # Container 2: Ứng dụng Web Spring Boot AKA-SYSTEM
  aka-app:
    build: .
    container_name: aka-system-web
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=aka;encrypt=true;trustServerCertificate=true;createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=AkaSystem@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=0
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath:seed_data_20_records.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true

volumes:
  mssql_data:
