spring.application.name=aka.system

server.port=8081

# DataSource Configuration (Dùng đúng 100% CSDL Local gốc: username sa, password 123)
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=aka;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Cấu hình Spring Boot Native SQL Initialization qua file data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true

# JavaMailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=canhthang457@gmail.com
spring.mail.password=pecf srpe aern sqfm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary Configuration
cloudinary.cloud-name=yapfrtzd
cloudinary.api-key=883868453768777
cloudinary.api-secret=2RxlBeBt4oH0DOur-YZFaXA9cbY

# Multipart File Upload Properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
